.TH "include/tuipp/private/macros.hpp" 3 "Version 0.0.1" "TUI++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/tuipp/private/macros.hpp
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTUIPP_NODISCARD\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define TUIPP_NODISCARD"

.SH "Author"
.PP 
Generated automatically by Doxygen for TUI++ from the source code\&.
