.TH "include/tuipp/console/print.hpp" 3 "TUI++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/tuipp/console/print.hpp
.SH SYNOPSIS
.br
.PP
\fR#include <string>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBtuipp\fP"
.br
.ti -1c
.RI "namespace \fBtuipp::console\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBtuipp::console::println\fP (const std::string &string='')"
.br
.RI "Print a string with a new line at the end\&. "
.ti -1c
.RI "void \fBtuipp::console::print\fP (const std::string &string='')"
.br
.RI "Print a string without a new line at the end\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for TUI++ from the source code\&.
