.TH "include/tuipp/print.hpp" 3 "TUI++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/tuipp/print.hpp \- A utility for printing output to the screen\&.  

.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBtuipp\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBtuipp::println\fP (const std::string &string='')"
.br
.RI "Print a string with a new line at the end\&. "
.ti -1c
.RI "void \fBtuipp::print\fP (const std::string &string='')"
.br
.RI "Print a string without a new line at the end\&. "
.in -1c
.SH "Detailed Description"
.PP 
A utility for printing output to the screen\&. 


.PP
\fBAuthor\fP
.RS 4
Giuliano De Amicis 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for TUI++ from the source code\&.
