.TH "tuipp" 3 "TUI++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tuipp
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBprintln\fP (const std::string &string='')"
.br
.RI "Print a string with a new line at the end (supports markup)\&. "
.ti -1c
.RI "void \fBprint\fP (const std::string &string='')"
.br
.RI "Print a string without a new line at the end (supports markup)\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "void tuipp::print (const std::string & string = \fR''\fP)"

.PP
Print a string without a new line at the end (supports markup)\&. 
.SS "Example:"
.PP
.nf
tuipp::print("[bold green]Hello, World![/]");
.fi
.PP
.SS "Styles:"
Foreground colors: \fRred\fP, \fRgreen\fP, \fRgrey\fP, \fRblue\fP, \fRmagenta\fP, \fRyellow\fP, \fRwhite\fP, \fRbright_red\fP, \fRbright_green\fP, \fRbright_grey\fP, \fRbright_blue\fP, \fRbright_magenta\fP, \fRbright_yellow\fP, \fRbright_cyan\fP, \fRbright_white\fP

.PP
Background colors: \fRbg_red\fP, \fRbg_green\fP, \fRbg_grey\fP, \fRbg_blue\fP, \fRbg_magenta\fP, \fRbg_yellow\fP, \fRbg_cyan\fP, \fRbg_white\fP

.PP
Effects: \fRbold\fP, \fRunderline\fP, \fRblink\fP, \fRitalic\fP

.PP
Reset: \fR/\fP

.PP
.PP

.PP
You can also escape markup brackets using a backslash:

.PP
.PP
.nf
tuipp::println("\\[bold red]Hello, World!\\[/]");
.fi
.PP

.PP
\fBParameters\fP
.RS 4
\fIstring\fP The string to be printed, it can be empty\&. 
.RE
.PP

.SS "void tuipp::println (const std::string & string = \fR''\fP)"

.PP
Print a string with a new line at the end (supports markup)\&. 
.SS "Example:"
.PP
.nf
tuipp::println("[bold red]Hello, World![/]");
.fi
.PP
.SS "Styles:"
Foreground colors: \fRred\fP, \fRgreen\fP, \fRgrey\fP, \fRblue\fP, \fRmagenta\fP, \fRyellow\fP, \fRwhite\fP, \fRbright_red\fP, \fRbright_green\fP, \fRbright_grey\fP, \fRbright_blue\fP, \fRbright_magenta\fP, \fRbright_yellow\fP, \fRbright_cyan\fP, \fRbright_white\fP

.PP
Background colors: \fRbg_red\fP, \fRbg_green\fP, \fRbg_grey\fP, \fRbg_blue\fP, \fRbg_magenta\fP, \fRbg_yellow\fP, \fRbg_cyan\fP, \fRbg_white\fP

.PP
Effects: \fRbold\fP, \fRunderline\fP, \fRblink\fP, \fRitalic\fP

.PP
Reset: \fR/\fP

.PP
.PP

.PP
You can also escape markup brackets using a backslash:

.PP
.PP
.nf
tuipp::println("\\[bold red]Hello, World!\\[/]");
.fi
.PP

.PP
\fBParameters\fP
.RS 4
\fIstring\fP The string to be printed, it can be empty\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for TUI++ from the source code\&.
