.TH "tuipp::widgets::Text" 3 "Version 0.0.1" "TUI++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tuipp::widgets::Text \- Just normal text!  

.SH SYNOPSIS
.br
.PP
.PP
Inherits tuipp::widgets::IRenderable\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBText\fP (std::string content)"
.br
.ti -1c
.RI "virtual void \fBrender\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Just normal text! 


.SS "Examples of use"
.PP
.nf
// Create the widget:
auto text = tuipp::widgets::Text("Text widget!");

// 3 ways of rendering it:
tuipp::Console console;
console << text;

tuipp::Console::println(text);

text\&.render();
.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "tuipp::widgets::Text::Text (std::string content)\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "virtual void tuipp::widgets::Text::render () const\fR [virtual]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for TUI++ from the source code\&.
