.TH "tuipp::widgets::Text" 3 "Version 0.0.1" "TUI++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tuipp::widgets::Text
.SH SYNOPSIS
.br
.PP
.PP
Inherits tuipp::widgets::IRenderable\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBText\fP (std::string content)"
.br
.ti -1c
.RI "virtual void \fBrender\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "tuipp::widgets::Text::Text (std::string content)\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "virtual void tuipp::widgets::Text::render ()\fR [virtual]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for TUI++ from the source code\&.
