.TH "tuipp" 3 "TUI++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tuipp
.SH SYNOPSIS
.br
.PP
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum class \fBState\fP { \fBTEXT\fP, \fBTAG\fP }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename CharT> std::basic_ostream< CharT > & \fBhandle_styles\fP (std::basic_ostream< CharT > &stream, const std::string &buffer)"
.br
.ti -1c
.RI "template<typename CharT> std::basic_ostream< CharT > & \fBparse_string\fP (std::basic_ostream< CharT > &stream, const std::string &string)"
.br
.ti -1c
.RI "void \fBprintln\fP (const std::string &string='')"
.br
.RI "Print a string with a new line at the end\&. "
.ti -1c
.RI "void \fBprint\fP (const std::string &string='')"
.br
.RI "Print a string without a new line at the end\&. "
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum class \fBtuipp::State\fP\fR [strong]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\f(BITEXT \fP
.TP
\f(BITAG \fP
.SH "Function Documentation"
.PP 
.SS "template<typename CharT> std::basic_ostream< CharT > & tuipp::handle_styles (std::basic_ostream< CharT > & stream, const std::string & buffer)"

.SS "template<typename CharT> std::basic_ostream< CharT > & tuipp::parse_string (std::basic_ostream< CharT > & stream, const std::string & string)"

.SS "void tuipp::print (const std::string & string = \fR''\fP)\fR [inline]\fP"

.PP
Print a string without a new line at the end\&. Example:

.PP
.PP
.nf
tuipp::print("[bold green]Hello, World![/]");
.fi
.PP

.PP
\fBParameters\fP
.RS 4
\fIstring\fP The string to be printed, it can be empty\&. 
.RE
.PP

.SS "void tuipp::println (const std::string & string = \fR''\fP)\fR [inline]\fP"

.PP
Print a string with a new line at the end\&. Example:

.PP
.PP
.nf
tuipp::println("[bold red]Hello, World![/]");
.fi
.PP

.PP
\fBParameters\fP
.RS 4
\fIstring\fP The string to be printed, it can be empty\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for TUI++ from the source code\&.
