.TH "tuipp::widgets::IRenderable" 3 "Version 0.0.1" "TUI++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tuipp::widgets::IRenderable \- The base class for every widgets, exposed so you can create your own!  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBtuipp::widgets::MarkupText\fP, \fBtuipp::widgets::Rule\fP, and \fBtuipp::widgets::Text\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBrender\fP () const =0"
.br
.in -1c
.SH "Detailed Description"
.PP 
The base class for every widgets, exposed so you can create your own! 
.SH "Member Function Documentation"
.PP 
.SS "virtual void tuipp::widgets::IRenderable::render () const\fR [pure virtual]\fP"

.PP
Implemented in \fBtuipp::widgets::MarkupText\fP, \fBtuipp::widgets::Rule\fP, and \fBtuipp::widgets::Text\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for TUI++ from the source code\&.
