.TH "tuipp::console" 3 "TUI++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tuipp::console
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBprintln\fP (const std::string &string='')"
.br
.RI "Print a string with a new line at the end\&. "
.ti -1c
.RI "void \fBprint\fP (const std::string &string='')"
.br
.RI "Print a string without a new line at the end\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "void tuipp::console::print (const std::string & string = \fR''\fP)"

.PP
Print a string without a new line at the end\&. 
.PP
\fBParameters\fP
.RS 4
\fIstring\fP The string to be printed, it can be empty\&. 
.RE
.PP

.SS "void tuipp::console::println (const std::string & string = \fR''\fP)"

.PP
Print a string with a new line at the end\&. 
.PP
\fBParameters\fP
.RS 4
\fIstring\fP The string to be printed, it can be empty\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for TUI++ from the source code\&.
